export type Sample = {
  "Characteristics[Animal Source]": string;
  "Characteristics[Genotype]": string;
  "Characteristics[Material Type]": string;
  "Characteristics[Organism]": string;
  "Characteristics[Sex]": string;
  "Characteristics[Strain]": string;
  "Comment[Dissection Dates]": string;
  "Comment[Euthanasia Dates]": string;
  "Comment[LAR Animal Receipt Date at Scrippts]": string;
  "Factor Value[Age]": string;
  "Factor Value[Dissection Condition]": string;
  "Factor Value[Duration]": string;
  "Factor Value[Euthanasia Location]": string;
  "Factor Value[Spaceflight]": string;
  "Parameter Value[Carcass Preservation Method]": string;
  "Parameter Value[Diet]": string;
  "Parameter Value[Euthanasia Method]": string;
  "Parameter Value[Feeding Schedule]": string;
  "Parameter Value[Light Cycle]": string;
  "Parameter Value[Sample Preservation Method]": string;
  "Parameter Value[Sample Storage Temperature]": string;
  "Protocol REF": string;
  "Protocol REF.1": string;
  "Sample Name": string;
  "Source Name": string;
  "Term Accession Number": string;
  "Term Accession Number.1": string;
  "Term Accession Number.10": string;
  "Term Accession Number.11": string;
  "Term Accession Number.12": string;
  "Term Accession Number.13": string;
  "Term Accession Number.14": string;
  "Term Accession Number.15": string;
  "Term Accession Number.2": string;
  "Term Accession Number.3": string;
  "Term Accession Number.4": string;
  "Term Accession Number.5": string;
  "Term Accession Number.6": string;
  "Term Accession Number.7": string;
  "Term Accession Number.8": string;
  "Term Accession Number.9": string;
  "Term Source REF": string;
  "Term Source REF.1": string;
  "Term Source REF.10": string;
  "Term Source REF.11": string;
  "Term Source REF.12": string;
  "Term Source REF.13": string;
  "Term Source REF.14": string;
  "Term Source REF.15": string;
  "Term Source REF.2": string;
  "Term Source REF.3": string;
  "Term Source REF.4": string;
  "Term Source REF.5": string;
  "Term Source REF.6": string;
  "Term Source REF.7": string;
  "Term Source REF.8": string;
  "Term Source REF.9": string;
  Unit: string;
  "Unit.1": string;
  "Unit.2": string;
  "Unit.3": string;
  index: number;
};
